// This file is automatically generated. Do not modify it manually.
export const firebaseConfig = {"projectId":"studio-9733913755-7af11","appId":"1:446514582348:web:15d3a58beab5ccbb0d35e9","apiKey":"AIzaSyDN7U4TaQ1oEPHSedrG1keMS1KASiXOgCM","authDomain":"studio-9733913755-7af11.firebaseapp.com","messagingSenderId":"446514582348"};
